### ISSUE TITLE
daily schedule not respected

### ISSUE THREAD

**Issue by fragolinux** [ryaneorth/k8s-scheduled-volume-snapshotter#26]
hi, i've this setup:

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: scheduled-volume-snapshotter
spec:
  gitImplementation: go-git
  interval: 24h
  ref:
    tag: v0.14.1
  timeout: 20s
  url: https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${release}
  namespace: ${namespace}
spec:
  interval: 1m
  timeout: 10m
  releaseName: ${release}
  targetNamespace: ${namespace}
  test:
    enable: true
    timeout: 10m
  chart:
    spec:
      chart: helm/charts/scheduled-volume-snapshotter
      sourceRef:
        kind: GitRepository
        name: scheduled-volume-snapshotter
      interval: 24h
  values:
    # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/tree/main/helm/charts/scheduled-volume-snapshotter
    schedule: "*/5 * * * *"
    rbac:
      enabled: true
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    logLevel: INFO
    startingDeadlineSeconds: 120
```

```
apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: ha-lts-snapshots-hourly
  namespace: ${namespace}
spec:
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter#scheduling-snapshots
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/blob/main/helm/charts/scheduled-volume-snapshotter/crds/scheduled-volume-snapshot-crd.yaml
  snapshotClassName: ${release}
  persistentVolumeClaimName: ha-core-data-lts
  snapshotFrequency: 1h
  snapshotRetention: 4h
  snapshotLabels:
    frequency: hourly
    envName: ${envName}
```

```
apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: ha-lts-snapshots-daily
  namespace: ${namespace}
spec:
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter#scheduling-snapshots
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/blob/main/helm/charts/scheduled-volume-snapshotter/crds/scheduled-volume-snapshot-crd.yaml
  snapshotClassName: ${release}
  persistentVolumeClaimName: ha-core-data-lts
  snapshotFrequency: 24h
  snapshotRetention: 7d
  snapshotLabels:
    frequency: daily
    envName: ${envName}
```

```
apiVersion: k8s.ryanorth.io/v1beta1
kind: ScheduledVolumeSnapshot
metadata:
  name: ha-lts-snapshots-weekly
  namespace: ${namespace}
spec:
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter#scheduling-snapshots
  # see https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/blob/main/helm/charts/scheduled-volume-snapshotter/crds/scheduled-volume-snapshot-crd.yaml
  snapshotClassName: ${release}
  persistentVolumeClaimName: ha-core-data-lts
  snapshotFrequency: 7d
  snapshotRetention: 30d
  snapshotLabels:
    frequency: weekly
    envName: ${envName}
```

but something is broken in how it manages daily snapshots... in image, the 1st 4 lines are good, it took a daily snapshot on days march 19, 20, 21, and 22, at about 13:10... then it went wrong, from the 5th lines and below, all those snapshots are all of day march 22, about 10-15 minutes far each from an other... 

<img width="1694" alt="image" src="https://github.com/ryaneorth/k8s-scheduled-volume-snapshotter/assets/21192010/a97460b9-f434-435d-839a-d3f09543870b">

nothing changed in deployed resources, and i've an other problem now, many snapshots are broken because it says an other one was already there on the same share, even if i completely remove all the offending snapshots (all those with ready: false)...

```
Status:
  Bound Volume Snapshot Content Name:  snapcontent-fae7a4ed-2fd3-47a3-b9e7-438ebcb3f63e
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume 172.16.0.102#mnt/kube_data#mongodb/lab/datadir-common-mongodb-hidden-0_pvc-0132f065-a5d2-49
0b-903c-2be6345dbd1e#pvc-0132f065-a5d2-490b-903c-2be6345dbd1e#: "rpc error: code = Internal desc = failed to mount src nfs server: rpc error: code = Aborted desc = An operation with the given
 Volume ID 172.16.0.102#mnt/kube_data#mongodb/lab/datadir-common-mongodb-hidden-0_pvc-0132f065-a5d2-490b-903c-2be6345dbd1e#pvc-0132f065-a5d2-490b-903c-2be6345dbd1e# already exists"
    Time:        2024-03-25T15:00:09Z
  Ready To Use:  false
```

what's going on? how to fix? Thanks in advance
